### ISSUE TITLE
IDNET dataset

### ISSUE THREAD

**Issue by ceciljc** [ethancaballero/gait-cycle-transfer#1]
may I know how the IDNet_dataset.csv looks like because when I downloaded the data it is still in log extension and have not preprocessed yet. 

df_data = pd.read_csv('IDNet_dataset.csv')

Those line of code seems like the dataset is different from the one I have downloaded fom this link:
http://signet.dei.unipd.it/human-sensing/

I hope you can help by replying this and shows how you prepare the data for cnn. Thank you

**Comment by ceciljc** [comment]
Sorry, I didn't read carefully for the explanation, just found the csv data. Thank you.

**Comment by OshanJayawardena** [comment]
> Sorry, I didn't read carefully for the explanation, just found the csv data. Thank you.

Do you have access to the .csv file in the drive?
